🚧 Update to SDK 26.1.100
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
💇🏽‍♂️🤹🏻‍♂️💏🏻1️⃣

Full error log:
Error:  asset 2022-7-25--0-33-41--42224b9c-bf5d-4d97-a242-d022bbf8eb5a/main.min.js 140 KiB [emitted] (name: main) 1 related asset
modules by path ./node_modules/ 120 KiB
modules by path ./node_modules/destroyable/dist/*.js 35.9 KiB 10 modules
modules by path ./node_modules/destroyable/dist/errors/*.js 2.59 KiB
./node_modules/destroyable/dist/errors/CollisionError.js 1.3 KiB [built] [code generated]
./node_modules/destroyable/dist/errors/NotFoundError.js 1.29 KiB [built] [code generated]
./node_modules/@collboard/modules-sdk/dist/runtime/runtime.js 54.7 KiB [built] [code generated]
./node_modules/xyzt/dist/main.js 26.4 KiB [built] [code generated]
modules by path ./src/ 10.5 KiB
modules with errors 7.92 KiB [errors]
./src/grid-type-attribute-module.tsx 1.32 KiB [built] [code generated] [2 errors]
./src/grid-size-attribute-module.tsx 1.06 KiB [built] [code generated] [2 errors]
./src/grid-polygon-drawing-tool-module.tsx 5.54 KiB [built] [code generated] [1 error]
./src/00-index.ts 258 bytes [built] [code generated]
./src/grid-polygon-art-module.tsx 2.38 KiB [built] [code generated]
./package.json 634 bytes [built] [code generated]

ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-polygon-drawing-tool-module.tsx
./src/grid-polygon-drawing-tool-module.tsx 65:63-116
[tsl] ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-polygon-drawing-tool-module.tsx(65,64)
TS2352: Conversion of type 'BehaviorSubject<attribute_value>' to type 'string' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
@ ./src/00-index.ts 5:0-45

ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-size-attribute-module.tsx
./src/grid-size-attribute-module.tsx 27:25-29
[tsl] ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-size-attribute-module.tsx(27,26)
TS2304: Cannot find name 'Icon'.
@ ./src/00-index.ts 4:0-43

ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-size-attribute-module.tsx
./src/grid-size-attribute-module.tsx 33:26-30
[tsl] ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-size-attribute-module.tsx(33,27)
TS2304: Cannot find name 'Icon'.
@ ./src/00-index.ts 4:0-43

ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-type-attribute-module.tsx
./src/grid-type-attribute-module.tsx 33:25-29
[tsl] ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-type-attribute-module.tsx(33,26)
TS2304: Cannot find name 'Icon'.
@ ./src/00-index.ts 3:0-43

ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-type-attribute-module.tsx
./src/grid-type-attribute-module.tsx 35:26-30
[tsl] ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-type-attribute-module.tsx(35,27)
TS2304: Cannot find name 'Icon'.
@ ./src/00-index.ts 3:0-43

webpack 5.35.1 compiled with 5 errors in 6483 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\polygon-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\polygon-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\polygon-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\polygon-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\polygon-drawing\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\polygon-drawing\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\polygon-drawing\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\polygon-drawing\node_modules\webpack\lib\Watching.js:201:28)