🚧 Update to SDK 27.15.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🍹🧝🏽‍♂️🎐🧑🏽‍🦼

Full error log:
Error:  asset 2022-8-29--11-11-18--59991e85-4b2c-4047-b899-f01ff640b810/main.min.js 171 KiB [emitted] (name: main) 1 related asset
runtime modules 57 bytes 1 module
modules by path ./node_modules/ 149 KiB
modules by path ./node_modules/destroyable/dist/*.js 35.9 KiB 10 modules
modules by path ./node_modules/destroyable/dist/errors/*.js 2.59 KiB 2 modules
./node_modules/@collboard/modules-sdk/dist/runtime/runtime.js 84.2 KiB [built] [code generated]
./node_modules/xyzt/dist/main.js 26.4 KiB [built] [code generated]
modules by path ./src/ 11.2 KiB
./src/00-index.ts 258 bytes [built] [code generated]
./src/grid-type-attribute-module.tsx 1.33 KiB [built] [code generated]
./src/grid-size-attribute-module.tsx 1.08 KiB [built] [code generated]
./src/grid-polygon-drawing-tool-module.tsx 6.11 KiB [built] [code generated]
./src/grid-polygon-art-module.tsx 2.38 KiB [built] [code generated] [3 errors]
./package.json 633 bytes [built] [code generated]
./assets/icons/Pavol_Hejny_icon_of_stained_glass_window_19982422-65e4-499d-94d2-076ebe150ab3.png 42 bytes [built] [code generated]

ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-polygon-art-module.tsx
./src/grid-polygon-art-module.tsx 6:4-18
[tsl] ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-polygon-art-module.tsx(6,5)
TS2305: Module '"@collboard/modules-sdk"' has no exported member 'nonceFunction3'.
@ ./src/00-index.ts 6:0-36

ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-polygon-art-module.tsx
./src/grid-polygon-art-module.tsx 7:4-18
[tsl] ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-polygon-art-module.tsx(7,5)
TS2305: Module '"@collboard/modules-sdk"' has no exported member 'nonceFunction4'.
@ ./src/00-index.ts 6:0-36

ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-polygon-art-module.tsx
./src/grid-polygon-art-module.tsx 8:4-18
[tsl] ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-polygon-art-module.tsx(8,5)
TS2305: Module '"@collboard/modules-sdk"' has no exported member 'nonceFunction5'.
@ ./src/00-index.ts 6:0-36

webpack 5.35.1 compiled with 3 errors in 6127 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\polygon-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\polygon-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\polygon-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\polygon-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\polygon-drawing\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\polygon-drawing\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\polygon-drawing\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\polygon-drawing\node_modules\webpack\lib\Watching.js:201:28)