🚧 Update to SDK 27.36.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
💂🏾🥬👨🏾‍✈️👨‍🔬

Full error log:
> grid-polygon-drawing@0.1.0 lint
> tslint -p tsconfig.json

C:/Users/me/work/collboard/polygon-drawing/src/grid-polygon-drawing-tool-module.tsx:84:29
ERROR: 84:29   no-console  Calls to 'console.log' are not allowed.
ERROR: 106:48  no-empty    block is empty