🚧 Update to SDK 26.7.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🍅🙇🏻‍♂️☝🏻💙

Full error log:
Error:  asset 2022-7-26--16-6-25--414cd116-8ba7-4c33-b541-9898219f4015/main.min.js 169 KiB [emitted] (name: main) 1 related asset
modules by path ./node_modules/ 149 KiB
modules by path ./node_modules/destroyable/dist/*.js 35.9 KiB 10 modules
modules by path ./node_modules/destroyable/dist/errors/*.js 2.59 KiB
./node_modules/destroyable/dist/errors/CollisionError.js 1.3 KiB [built] [code generated]
./node_modules/destroyable/dist/errors/NotFoundError.js 1.29 KiB [built] [code generated]
./node_modules/@collboard/modules-sdk/dist/runtime/runtime.js 83.6 KiB [built] [code generated]
./node_modules/xyzt/dist/main.js 26.4 KiB [built] [code generated]
modules by path ./src/ 10.9 KiB
./src/00-index.ts 258 bytes [built] [code generated]
./src/grid-type-attribute-module.tsx 1.33 KiB [built] [code generated]
./src/grid-size-attribute-module.tsx 1.08 KiB [built] [code generated]
./src/grid-polygon-drawing-tool-module.tsx 5.55 KiB [built] [code generated]
./src/grid-polygon-art-module.tsx 2.67 KiB [built] [code generated] [1 error]
./package.json 632 bytes [built] [code generated]

ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-polygon-art-module.tsx
./src/grid-polygon-art-module.tsx 19:22-36
[tsl] ERROR in C:\Users\me\work\collboard\polygon-drawing\src\grid-polygon-art-module.tsx(19,23)
TS2552: Cannot find name 'nonceFunction5'. Did you mean 'nonceFunction3'?
@ ./src/00-index.ts 6:0-36

webpack 5.35.1 compiled with 1 error in 6437 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\polygon-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\polygon-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\polygon-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\polygon-drawing\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\polygon-drawing\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\polygon-drawing\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\polygon-drawing\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\polygon-drawing\node_modules\webpack\lib\Watching.js:201:28)